### PR TITLE
FIX #292 - json requestOne fix

### LINKED ISSUE #292: Argument handling
#286 contribution (thank you @basti1302)  pointed out that argument handling is currently too loose. That contribution addressed `publish`, but the same type of defect is apparent also on `subscribe`, `request`, etc.

### PR DESCRIPTION
**Pull request by aricart**
For JSON clients, a number parameter could be a value. The NATS library incorrectly took the first number as the timeout.

### CODE REVIEW

**Comment by aricart** [comment]
@kozlovic  sorry - I had a git explosion trying to get it to rebase, so I made a new PR.
I have updated the tests to cover the possible 'correct' number of arguments

File: lib/nats.js [hunk 1]
```diff
@@ -1884,27 +1884,65 @@ Client.prototype.requestOne = function(subject, opt_msg, opt_options, timeout, c
...
+    const idx = lastIndexOf(args, (v) => typeof v === 'function');
+
+    // found a function, at the last index
+    if (idx !== -1) {
+        a[maxArgs - 1] = args[idx];
+        for (let i = 0; i < idx; i++) {
+            a[i] = args[i];
+        }
+    } else {
+        for (let i=0; i < args.length; i++) {
```
Comment (kozlovic) [inline lib/nats.js]: Did you not say that you could return args here?

File: test/basics.js [hunk 2]
```diff
@@ -877,4 +877,117 @@ describe('Basics', function() {
...
+
+                nc.requestOne(subj, 'a', {queue: 'worker'}, 1000, h);
+                nc.requestOne(subj, {}, {queue: 'worker'}, 1000, h);
+                nc.requestOne(subj, 10, {queue: 'worker'}, 1000, h);
+            });
+        });
+    });
+
+    it('json json old requests', function(done) {
+        const nc = NATS.connect({port: PORT, json: true, useOldRequestStyle: true});
```
Comment (kozlovic) [inline test/basics.js]: Would have been nice to have a function that is shared by those 2 `if()` tests and simply ass the `useOldRequestStyle` option to that common function.

File: lib/nats.js (hunk 1 above)
Comment (aricart) [reply lib/nats.js]: rethought that at least we get a sanitized version of the args - (it will be the expected length regardless of what they passed)

File: test/basics.js (hunk 2 above)
Comment (aricart) [reply test/basics.js]: I'll refactor all that soon - and get the deprecated junk out of there.
