### PR TITLE
FIX #289 -  permissions error aborted inbound processing

### LINKED ISSUE #289: Incorrect handling of the permission errors
After the `permission_error` is handled, the `inbound` buffer is not cleared and all subsequent data appended to that buffer is ignored.

After @aricart 's explanation changing this to: after 1 `permission_error` is encountered, all subsequent buffer reads result in `permission_errors`.

### PR DESCRIPTION
**Pull request by aricart**
if a permissions error was encountered by the client, the connection remained open but processing of inbound was exited.

### CODE REVIEW

File: test/perms.js [hunk 1]
```diff
@@ -87,4 +87,58 @@ describe('Auth Basics', function() {
...
+
+        nc.publish('bar');
+        nc.publish('foo');
+        nc.publish('bar');
+        nc.subscribe('foo', () => {});
+        nc.publish('bar');
+        nc.flush(() => {
+            nc.close();
+            if (errs.length !== 2) {
+                done(new Error("expected one permission error"));
```
Comment (andriy-bulynko) [inline test/perms.js]: Should this be:
```suggestion
                done(new Error("expected two permission errors"));
```

**Comment by aricart** [comment]
This matches the nats.ts handling (so nats.ts doesn't require a fix).

https://github.com/nats-io/nats.ts/blob/master/src/protocolhandler.ts#L642
https://github.com/nats-io/nats.ts/blob/master/src/protocolhandler.ts#L979

File: test/perms.js (hunk 1 above)
Comment (aricart) [reply test/perms.js]: Yes it should - thanks @andriy-bulynko
